// [arquivo, nome, categoria, subcategoria, estações(V O I P), novo?, detalhes pra IA]
window.CATALOGO = [
["p000", "Gola alta preta cropped", "top", "manga longa", "OI"],
["p001", "Short preto de alfaiataria", "bottom", "short", "VP"],
["p002", "Blusa preta ombro a ombro", "top", "manga longa", "VOP"],
["p003", "Gorro preto", "chapeu", "gorro", "I"],
["p004", "Tomara que caia preto", "top", "alça", "VP"],
["p005", "Blusa preta decote V manga longa", "top", "alça", "OIP"],
["p006", "Short preto de alfaiataria", "bottom", "short", "VP"],
["p007", "Regata vinho de alcinha", "top", "alça", "VOP"],
["p008", "Short preto de alfaiataria", "bottom", "short", "VP"],
["p009", "Blusa preta ombro a ombro", "top", "manga longa", "OIP"],
["p010", "Calça pantalona preta", "bottom", "calça", "VOIP"],
["p011", "Blusa preta manga bufante", "top", "manga longa", "OP"],
["p012", "Calça pantalona preta", "bottom", "calça", "VOIP"],
["p013", "Gola alta preta canelada", "top", "manga longa", "OI"],
["p014", "Saia preta com cinto dourado", "bottom", "saia", "VOIP"],
["p015", "Vestido preto manga transparente", "vestido", "vestido", "OI"],
["p016", "Blazer preto acetinado", "casaco", "blazer", "OI"],
["p017", "Vestido preto gola alta", "vestido", "vestido", "OI"],
["p018", "Top verde musgo", "top", "alça", "VP"],
["p019", "Blusa preta com laço", "top", "manga longa", "OP"],
["p020", "Vestido de veludo verde", "vestido", "vestido", "OI"],
["p021", "Camiseta preta com logo", "top", "manga curta", "VOP"],
["p022", "Camiseta preta básica", "top", "manga curta", "VOP"],
["p023", "Camiseta preta estampada", "top", "manga curta", "VOP"],
["p024", "Calça preta social", "bottom", "calça", "VOIP"],
["p025", "Blusa preta decote V manga longa", "top", "alça", "OIP"],
["p026", "Vestido preto manga transparente", "vestido", "vestido", "OI"],
["p027", "Jaqueta utilitária preta", "casaco", "jaqueta", "OI"],
["p028", "Tomara que caia vinho", "top", "alça", "VOP"],
["p029", "Vestido preto com saia de couro", "vestido", "vestido", "OI"],
["p030", "Parka preta com capuz", "casaco", "jaqueta", "OI"],
["p031", "Short branco com botões", "bottom", "short", "VP"],
["p032", "Tênis preto esportivo", "calcado", "tênis", "VOIP"],
["p033", "Blazer vinho com cinto", "casaco", "blazer", "OI"],
["p034", "Bota preta cano alto", "calcado", "bota", "OI"],
["p035", "Camiseta branca com estampa", "top", "manga curta", "VP"],
["p036", "Top verde musgo", "top", "alça", "VP"],
["p037", "Regata branca de alcinha", "top", "alça", "VP"],
["p038", "Coturno preto anabela", "calcado", "bota", "OI"],
["p039", "Mocassim preto com fivela", "calcado", "sapato", "OIP"],
["p040", "Bolsa de notebook preta", "acessorio", "bolsa", "VOIP"],
["p041", "Coturno preto", "calcado", "bota", "OI"],
["p042", "Jaqueta de couro preta", "casaco", "jaqueta", "OI"],
["p043", "Blusa branca manga bufante", "top", "manga longa", "VOP"],
["p044", "Calça pantalona vinho", "bottom", "calça", "OIP"],
["p045", "Short branco com laço", "bottom", "short", "VP"],
["p046", "Calça pantalona vinho", "bottom", "calça", "OIP"],
["p047", "Camisa branca manga 3/4", "top", "manga longa", "VOP"],
["p048", "Regata vinho de alcinha", "top", "alça", "VOP"],
["p049", "Top branco com laço", "top", "manga longa", "VP"],
["p050", "Cropped branco manga bufante", "top", "manga longa", "VOP"],
["p051", "Blusa vermelha drapeada", "top", "manga longa", "VOP"],
["p052", "Saia branca com cinto", "bottom", "saia", "VP"],
["p053", "Calça branca de alfaiataria", "bottom", "calça", "VP"],
["p054", "Top verde com amarração", "top", "alça", "VP"],
["p055", "Short marrom canelado", "bottom", "short", "VP"],
["p056", "Cardigã creme de malha", "casaco", "cardigã", "OP"],
["p057", "Saia longa branca de tule", "bottom", "saia", "VP"],
["p058", "Suéter branco de tricô", "top", "manga longa", "OI"],
["p059", "Calça branca pantalona", "bottom", "calça", "VP"],
["p060", "Chinelo preto", "calcado", "chinelo", "V"],
["p061", "Tênis branco chunky", "calcado", "tênis", "VOIP"],
["p062", "Kimono floral preto", "casaco", "kimono", "VP"],
["p063", "Top marrom com torção", "top", "alça", "VP"],
["p064", "Short jeans escuro", "bottom", "short", "VP"],
["p066", "Corselet terracota", "top", "alça", "VP"],
["p067", "Tomara que caia marrom", "top", "alça", "VP"],
["p068", "Cachecol marrom com franjas", "acessorio", "lenço", "OI"],
["p069", "Cropped branco com recorte", "top", "alça", "VP"],
["p070", "Camiseta marrom Salmos", "top", "manga curta", "VOP"],
["p071", "Chinelo branco", "calcado", "chinelo", "V"],
["p072", "Blusa preta decote V manga longa", "top", "alça", "OIP"],
["p073", "Saia midi branca acetinada", "bottom", "saia", "VP"],
["p074", "Vestido midi branco", "vestido", "vestido", "VP"],
["p075", "Cinto marrom fivela prateada", "acessorio", "cinto", "VOIP"],
["p076", "Vestido turquesa estampado", "vestido", "vestido", "V"],
["p077", "Calça off-white com barra", "bottom", "calça", "VOP"],
["p078", "Tênis branco", "calcado", "tênis", "VOIP"],
["p079", "Bota branca de neve", "calcado", "bota", "I"],
["p080", "Kimono floral manga ampla", "casaco", "kimono", "VP"],
["p081", "Vestido floral azul", "vestido", "vestido", "VP"],
["p082", "Calça verde militar", "bottom", "calça", "OIP"],
["p083", "Echarpe preta", "acessorio", "lenço", "OI"],
["p084", "Macaquinho azul estampado", "vestido", "macaquinho", "VP"],
["p085", "Blusa de tule bordada preta", "top", "alça", "VOP"],
["p086", "Blusa vermelha sem manga", "top", "manga longa", "VP"],
["p087", "Sandália gladiadora preta", "calcado", "sandália", "VP"],
["p088", "Blusa floral amarrada", "top", "manga curta", "VP"],
["p089", "Blusa verde oliva bufante", "top", "manga longa", "OP"],
["p090", "Short jeans claro com cinto", "bottom", "short", "VP"],
["p091", "Corselet vermelho acetinado", "top", "alça", "VOP"],
["p092", "Gola alta cinza com amarração", "top", "alça", "OI"],
["p093", "Bolsa preta estruturada", "acessorio", "bolsa", "VOIP"],
["p094", "Calça jogger cinza", "bottom", "calça", "OIP"],
["p095", "Vestido chemise terracota", "vestido", "vestido", "OP"],
["p096", "Chinelo preto com brilho", "calcado", "chinelo", "V"],
["p097", "Blusa de girassóis", "top", "manga curta", "V"],
["p098", "Camisa listrada com flores", "top", "manga longa", "VP"],
["p099", "Top pink de paetê", "top", "alça", "V"],
["p100", "Short bege", "bottom", "short", "VP"],
["p101", "Top listrado com folhagem", "top", "alça", "V"],
["p102", "Cinto preto fivela dourada", "acessorio", "cinto", "VOIP"],
["p103", "Vestido midi floral rosa", "vestido", "vestido", "VP"],
["p104", "Calça jeans wide leg clara", "bottom", "calça", "VOP"],
["p105", "Jaqueta jeans clara", "casaco", "jaqueta", "VOP"],
["p106", "Jaqueta militar com pelo", "casaco", "jaqueta", "OI"],
["p107", "Blusa azul com bolsos", "top", "manga longa", "OP"],
["p108", "Top acetinado cobre", "top", "alça", "VP"],
["p110", "Camisa xadrez preto e branco", "top", "manga longa", "OIP"],
["p111", "Calça camel wide leg", "bottom", "calça", "OIP"],
["p112", "Óculos gatinho bege", "acessorio", "óculos", "VP"],
["p113", "Blusa de tule transparente", "top", "manga longa", "OP"],
["p114", "Calça bege de alfaiataria", "bottom", "calça", "VOP"],
["p115", "Calça caramelo", "bottom", "calça", "OP"],
["p116", "Calça jeans clara reta", "bottom", "calça", "VOP"],
["p117", "Short xadrez tweed", "bottom", "short", "OP"],
["p118", "Cinto marrom fivela dourada", "acessorio", "cinto", "VOIP"],
["p119", "Sandália branca salto bloco", "calcado", "sandália", "VP"],
["p120", "Calça camel wide leg", "bottom", "calça", "OIP"],
["p121", "Blazer cinza mescla", "casaco", "blazer", "OIP"],
["p122", "Lenço vermelho de Roma", "acessorio", "lenço", "OI"],
["p123", "Lenço pied-de-poule", "acessorio", "lenço", "OI"],
["p124", "Blazer xadrez marrom", "casaco", "blazer", "OI"],
["p125", "Lenço estampado dourado", "acessorio", "lenço", "OIP"],
["p126", "Tomara que caia listrado", "top", "alça", "VP"],
["p127", "Blazer xadrez marrom", "casaco", "blazer", "OI"],
["p128", "Camisa do Grêmio Suárez", "top", "manga curta", "VOIP"],
["p129", "Short caramelo de alfaiataria", "bottom", "short", "VP"],
["p130", "Camisa caqui oversized", "top", "manga longa", "OP"],
["p131", "Top roxo com laço", "top", "alça", "VP"],
["p132", "Cinto preto fivela western", "acessorio", "cinto", "VOIP"],
["p133", "Camisa estampa abstrata", "top", "manga longa", "VP"],
["p134", "Corselet floral bege", "top", "alça", "VP"],
["p135", "Top zigue-zague", "top", "alça", "VP"],
["p136", "Camisa bege de linho", "top", "manga longa", "VP"],
["p137", "Blazer pink", "casaco", "blazer", "VP"],
["p138", "Cinto preto com tachas douradas", "acessorio", "cinto", "VOIP"],
["p139", "Blusa ombro a ombro floral rosas", "top", "manga curta", "VP"],
["p140", "Cinto preto fivela western", "acessorio", "cinto", "VOIP"],
["p141", "Camisa do Grêmio", "top", "manga curta", "VOIP"],
["p142", "Calça estampa abstrata", "bottom", "calça", "VP"],
["p143", "Jaqueta acolchoada bege", "casaco", "jaqueta", "OI"],
["p144", "Argolas douradas", "joia", "brinco", "VOIP"],
["p145", "Blazer mostarda", "casaco", "blazer", "OP"],
["p146", "Calça caramelo jogger", "bottom", "calça", "OP"],
["p147", "Top turquesa lifemom", "top", "alça", "V"],
["p148", "Casaco camel longo", "casaco", "sobretudo", "OI"],
["p149", "Bolsa de couro marrom", "acessorio", "bolsa", "VOIP"],
["p150", "Rasteira dourada", "calcado", "sandália", "VP"],
["p151", "Bolsa bege estruturada", "acessorio", "bolsa", "VOIP"],
["p153", "Casaco camel trespassado", "casaco", "sobretudo", "I"],
["p154", "Gola alta caramelo sem manga", "top", "manga longa", "OP"],
["p155", "Blazer camel", "casaco", "blazer", "OIP"],
["p157", "Sandália nude com glitter", "calcado", "sandália", "VP"],
["p158", "Sandália pink salto fino", "calcado", "sandália", "VP"],
["p159", "Cinto marrom fino", "acessorio", "cinto", "VOIP"],
["p160", "Mochila caramelo", "acessorio", "bolsa", "VOIP"],
["p167", "Blazer tweed bege", "casaco", "blazer", "OIP"],
["p168", "Vestido longo verde sálvia", "vestido", "vestido", "VP"],
["p169", "Short xadrez tweed", "bottom", "short", "OP"],
["p173", "Calça verde militar", "bottom", "calça", "OIP"],
["p179", "Saia midi marrom franzida", "bottom", "saia", "VOP"],
["p182", "Óculos redondo dourado", "acessorio", "óculos", "VOP"],
["p183", "Colar dourado três fios", "joia", "colar", "VOIP"],
["p184", "Colar corrente grossa", "joia", "colar", "VOIP"],
["p189", "Cinturão corrente dourada", "acessorio", "cinto", "VOIP"],
["p190", "Colar corrente grossa", "joia", "colar", "VOIP"],
["p191", "Tomara que caia creme", "top", "alça", "VP"],
["p194", "Colar dourado com medalha", "joia", "colar", "VOIP"],
["p197", "Saia midi animal print", "bottom", "saia", "VOP"],
["p207", "Cinturão corrente dourada", "acessorio", "cinto", "VOIP"],
["p209", "Colar dourado duplo fino", "joia", "colar", "VOIP"],
["p214", "Short branco com botões", "bottom", "short", "VP"],
["p215", "Óculos de grau dourado", "acessorio", "óculos", "VOIP"],
["g033", "Blazer creme aberto", "casaco", "blazer", "VOP"],
["g034", "Blazer camel de alfaiataria", "casaco", "blazer", "OIP"],
["g035", "Camisa camel oversized", "top", "manga longa", "OP"],
["g036", "Blazer verde oliva", "casaco", "blazer", "OIP"],
["g037", "Blazer caqui", "casaco", "blazer", "OIP"],
["g039", "Short creme de alfaiataria", "bottom", "short", "VP"],
["item_111", "Saia xadrez cinza", "bottom", "saia", "OI"],
["item_114", "Blusa de girassóis", "top", "alça", "V"],
["item_118", "Tomara que caia listrado", "top", "alça", "VP"],
["item_122", "Top zigue-zague", "top", "alça", "VP"],
["new_body_marrom", "Body de tule marrom", "top", "manga longa", "OIP", 2, "tule transparente marrom, gola alta, manga longa, corpo de body cavado; o tecido tem que aparecer transparente, não pode virar malha opaca"],
["new_golaalta_chumbo", "Gola alta preta", "top", "manga longa", "OI", 2, "canelada preta de verdade, não cinza nem chumbo; malha canelada fina, gola alta, manga longa, caimento justo"],
["new_golaalta_marrom", "Gola alta marrom", "top", "manga longa", "OI", 2, "malha canelada marrom escuro, gola alta, manga longa, caimento justo"],
["new_golaalta_nude", "Gola alta nude", "top", "manga longa", "OI", 2, "malha lisa nude, gola alta, manga longa, caimento justo"],
["new_golaalta_offwhite", "Gola alta off-white", "top", "manga longa", "OI", 2, "malha canelada off-white, gola alta, manga longa, caimento justo"],
["new_bone_ny", "Boné bege NEW YORK", "chapeu", "boné", "VOIP", 2, "boné aba curva bege cru com bordado preto em duas linhas NEW YORK e N.Y."],
["new_bone_roxo", "Boné roxo too busy making money", "chapeu", "boné", "VOIP", 2, "boné aba curva roxo magenta com bordado branco em duas linhas, too busy making money, fonte serifada minúscula"],
["new_golaalta_vinho", "Gola alta vinho", "top", "manga longa", "OI", 2, "malha canelada vinho, gola alta, manga longa, caimento justo"],
["new_jaqueta_couro_marrom", "Jaqueta de couro marrom", "casaco", "jaqueta", "OI", 2, "couro marrom, modelo motociclista com zíper diagonal e lapela"],
["new_golaalta_violeta", "Gola alta violeta", "top", "manga longa", "OIP", 2, "malha lisa violeta, gola alta, manga longa"],
["new_body_tule_preto", "Body de tule rendado preto", "top", "manga longa", "OIP", 2, "tule preto rendado transparente, gola alta, manga longa, com top preto opaco por baixo no busto"],
["new_body_regata_preto", "Body regata preto", "top", "alça", "VOIP", 2, "body regata preto liso, gola redonda alta, cava alta tipo nadador, malha canelada fosca"],
["new_body_regata_branco", "Body regata branco", "top", "alça", "VOIP", 2, "body regata branco liso, gola redonda alta, cava alta tipo nadador, malha fosca"],
["new_body_alca_preto", "Body de alça preto", "top", "alça", "VOIP", 2, "body de alcinha fina preto, decote reto, malha lisa fosca"],
["new_body_alca_marrom", "Body de alça marrom", "top", "alça", "VOIP", 2, "body de alcinha fina marrom chocolate, decote reto, malha lisa fosca"],
["new_cropped_verde_bolinhas", "Cropped verde de bolinhas", "top", "manga longa", "VOP", 2, "cropped verde militar de tule com bolinhas em relevo plumeti, decote V franzido, manga bufante com punho"],
["new_blusa_tule_marrom_botoes", "Blusa de tule marrom com botões", "top", "manga longa", "VOP", 2, "tule transparente marrom terracota, decote V com botões forrados, babados em cascata na frente e nas mangas"],
["new_colete_branco", "Colete off-white", "casaco", "colete", "VOIP", 2, "colete de alfaiataria off-white sem manga, decote V, quatro botões brancos, barra em bico"],
["new_blusa_vinho", "Blusa frente única vinho", "top", "alça", "VOP", 2, "top de amarrar no pescoço com tiras finas, decote drapeado, costas abertas, tecido duna fosco sem brilho, vinho"],
["new_body_alca_branco", "Body de alça branco", "top", "alça", "VOIP", 2, "body de alcinha fina branco, decote reto, malha lisa fosca"],
["new_short_marrom_coracao", "Short marrom com corações", "bottom", "short", "VOP", 2, "short jeans marrom escuro cintura alta, barra dobrada, bordado de corações vazados em linha bege no bolso da frente"],
["new_trico_golav_preto", "Tricô gola V preto", "top", "manga longa", "OI", 2, "suéter de tricô preto canelado, decote V profundo e cavado, manga longa, caimento solto"],
["new_sapatilha_slingback", "Sapatilha slingback off-white", "calcado", "sapato", "VOP", 2, "sapatilha bico fino off-white, aberta atrás com tirinha no calcanhar e fivela dourada, salto baixo"],
["new_rasteira_branca", "Rasteirinha branca", "calcado", "sandália", "VP", 2, "rasteirinha slide de couro off-white com tira larga recortada em H, bico quadrado, sem salto"],
["new_rasteira_marrom_medalhao", "Rasteirinha marrom com medalhões", "calcado", "sandália", "VP", 2, "rasteirinha de dedo de couro marrom com palmilha preta e medalhões redondos prateados na tira da frente, tirinha no tornozelo"],
["new_oculos_redondo_dourado", "Óculos redondo dourado", "acessorio", "óculos", "VOP", 2, "óculos de sol redondo com armação dourada fina e lente marrom degradê"],
["new_oculos_gatinho_preto", "Óculos gatinho preto", "acessorio", "óculos", "VP", 2, "óculos de sol gatinho de acetato preto com lente escura"],
["new_relogio_dourado", "Relógio dourado e prata", "joia", "relógio", "VOIP", 2, "relógio de pulso com caixa quadrada, mostrador branco com números romanos, pulseira de elos em dois tons, dourado e prata"],
["new_max_tee_vintage", "Max tee vintage branca", "top", "manga curta", "VOP", 2, "camiseta branca oversized comprida, gola redonda, manga curta ampla, estampa preta no peito com KEEP CLASSIC ALIVE, VINTAGE em letras grandes, carro clássico e Live A Modern Life"],
["new_bota_marrom_curta", "Bota marrom de cano curto", "calcado", "bota", "OIP", 2, "bota de cano curto até o tornozelo, couro marrom escuro, bico fino, salto alto fino, zíper lateral"],
["new_legging_preta", "Legging preta", "bottom", "calça", "OIP", 2, "legging preta básica, justa, cintura alta, até o tornozelo, malha lisa fosca sem brilho"],
["new_trico_branco_longo", "Tricô branco comprido", "top", "manga longa", "OI", 2, "suéter de tricô creme off-white comprido tipo vestido curto, gola alta dobrada, tranças cabo na frente e nas mangas, malha grossa, manga longa ampla"],
["new_tenis_samba", "Tênis retrô branco e marrom", "calcado", "tênis", "VOIP", 2, "tênis casual retrô de camurça branco off-white com três listras laterais marrom escuro, sola de goma bege, bico em T marrom, sem logos"],
["new_cardiga_trico_bege", "Cardigã tricô marrom taupe", "casaco", "cardigã", "OIP", 2, "cardigã cropped de tricô canelado marrom taupe mocha, decote V, manga longa com punho, botões pequenos dourados, comprimento na cintura"],
["new_calca_trico_bege", "Calça tricô marrom taupe", "bottom", "calça", "OIP", 2, "calça de tricô canelado marrom taupe mocha, wide leg, cintura alta elástica, malha canelada vertical, comprimento longo"],
["new_cachecol_xadrez", "Cachecol xadrez marrom", "acessorio", "lenço", "OI", 2, "cachecol manta oversized de lã xadrez, quadros grandes em bege cru, camel, marrom escuro e preto, franjas nas pontas"],
["new_cachecol_branco", "Cachecol branco", "acessorio", "lenço", "OI", 2, "cachecol de tricô branco off-white liso, canelado macio, retangular longo, franjas curtas nas pontas"],
];

// looks já gerados no avatar: chave = ids das peças em ordem alfabética
window.LOOKS_PRONTOS = {
  "new_jaqueta_couro_marrom,new_oculos_gatinho_preto,p024,p058,p061": "img/look_trico_couro_preta.webp",
  "p013,p034,p194,p197": "img/look_golaalta_animalprint.webp",
  "new_oculos_gatinho_preto,p010,p013,p038,p153": "img/look_casaco_camel_preto.webp",
  "new_golaalta_offwhite,new_oculos_gatinho_preto,p061,p111,p148": "img/look_casaco_camel_bege.webp",
  "g037,p013,p024,p034": "img/look_blazer_caqui_preto.webp",
  "new_golaalta_marrom,new_jaqueta_couro_marrom,p061,p114": "img/look_golaalta_marrom_couro.webp",
  "new_jaqueta_couro_marrom,new_oculos_redondo_dourado,p058,p061,p111,p149,p194": "img/look_trico_couro_camel.webp",
  "new_oculos_redondo_dourado,new_trico_golav_preto,p047,p078,p104": "img/look_camisa_trico_jeans.webp",
};
