// [arquivo, nome, categoria, subcategoria, estações(V O I P), novo?]
window.CATALOGO = [
["item_114","Blusa de girassóis","top","alça","V"],
["p085","Blusa de tule bordada preta","top","alça","VOP"],
["p005","Blusa preta decote V manga longa","top","alça","OIP"],
["p025","Blusa preta decote V manga longa","top","alça","OIP"],
["p072","Blusa preta decote V manga longa","top","alça","OIP"],
["p134","Corselet floral bege","top","alça","VP"],
["p166","Corselet floral bege","top","alça","VP"],
["p066","Corselet terracota","top","alça","VP"],
["p091","Corselet vermelho acetinado","top","alça","VOP"],
["p069","Cropped branco com recorte","top","alça","VP"],
["p092","Gola alta cinza com amarração","top","alça","OI"],
["p037","Regata branca de alcinha","top","alça","VP"],
["p007","Regata vinho de alcinha","top","alça","VOP"],
["p048","Regata vinho de alcinha","top","alça","VOP"],
["p191","Tomara que caia creme","top","alça","VP"],
["p126","Tomara que caia listrado","top","alça","VP"],
["item_118","Tomara que caia listrado","top","alça","VP"],
["p067","Tomara que caia marrom","top","alça","VP"],
["p004","Tomara que caia preto","top","alça","VP"],
["p028","Tomara que caia vinho","top","alça","VOP"],
["p108","Top acetinado cobre","top","alça","VP"],
["p178","Top acetinado cobre","top","alça","VP"],
["p101","Top listrado com folhagem","top","alça","V"],
["p063","Top marrom com torção","top","alça","VP"],
["p099","Top pink de paetê","top","alça","V"],
["p131","Top roxo com laço","top","alça","VP"],
["p147","Top turquesa lifemom","top","alça","V"],
["p054","Top verde com amarração","top","alça","VP"],
["p018","Top verde musgo","top","alça","VP"],
["p036","Top verde musgo","top","alça","VP"],
["p135","Top zigue-zague","top","alça","VP"],
["item_122","Top zigue-zague","top","alça","VP"],
["p097","Blusa de girassóis","top","manga curta","V"],
["p088","Blusa floral amarrada","top","manga curta","VP"],
["p139","Blusa ombro a ombro floral rosas","top","manga curta","VP"],
["p141","Camisa do Grêmio","top","manga curta","VOIP"],
["p128","Camisa do Grêmio Suárez","top","manga curta","VOIP"],
["p035","Camiseta branca com estampa","top","manga curta","VP"],
["p070","Camiseta marrom Salmos","top","manga curta","VOP"],
["p022","Camiseta preta básica","top","manga curta","VOP"],
["p021","Camiseta preta com logo","top","manga curta","VOP"],
["p023","Camiseta preta estampada","top","manga curta","VOP"],
["p107","Blusa azul com bolsos","top","manga longa","OP"],
["p043","Blusa branca manga bufante","top","manga longa","VOP"],
["p113","Blusa de tule transparente","top","manga longa","OP"],
["p019","Blusa preta com laço","top","manga longa","OP"],
["p011","Blusa preta manga bufante","top","manga longa","OP"],
["p002","Blusa preta ombro a ombro","top","manga longa","VOP"],
["p009","Blusa preta ombro a ombro","top","manga longa","OIP"],
["p089","Blusa verde oliva bufante","top","manga longa","OP"],
["p051","Blusa vermelha drapeada","top","manga longa","VOP"],
["p086","Blusa vermelha sem manga","top","manga longa","VP"],
["new_body_marrom","Body manga longa marrom","top","manga longa","OIP",1],
["p136","Camisa bege de linho","top","manga longa","VP"],
["p047","Camisa branca manga 3/4","top","manga longa","VOP"],
["g035","Camisa camel oversized","top","manga longa","OP"],
["p130","Camisa caqui oversized","top","manga longa","OP"],
["p133","Camisa estampa abstrata","top","manga longa","VP"],
["p098","Camisa listrada com flores","top","manga longa","VP"],
["p110","Camisa xadrez preto e branco","top","manga longa","OIP"],
["p050","Cropped branco manga bufante","top","manga longa","VOP"],
["p154","Gola alta caramelo sem manga","top","manga longa","OP"],
["new_golaalta_chumbo","Gola alta chumbo","top","manga longa","OI",1],
["new_golaalta_marrom","Gola alta marrom","top","manga longa","OI",1],
["new_golaalta_nude","Gola alta nude","top","manga longa","OI",1],
["new_golaalta_offwhite","Gola alta off-white","top","manga longa","OI",1],
["p013","Gola alta preta canelada","top","manga longa","OI"],
["p000","Gola alta preta cropped","top","manga longa","OI"],
["p058","Suéter branco de tricô","top","manga longa","OI"],
["p049","Top branco com laço","top","manga longa","VP"],
["p114","Calça bege de alfaiataria","bottom","calça","VOP"],
["p053","Calça branca de alfaiataria","bottom","calça","VP"],
["p059","Calça branca pantalona","bottom","calça","VP"],
["p111","Calça camel wide leg","bottom","calça","OIP"],
["p120","Calça camel wide leg","bottom","calça","OIP"],
["p115","Calça caramelo","bottom","calça","OP"],
["p146","Calça caramelo jogger","bottom","calça","OP"],
["p142","Calça estampa abstrata","bottom","calça","VP"],
["p116","Calça jeans clara reta","bottom","calça","VOP"],
["p104","Calça jeans wide leg clara","bottom","calça","VOP"],
["p094","Calça jogger cinza","bottom","calça","OIP"],
["p077","Calça off-white com barra","bottom","calça","VOP"],
["p010","Calça pantalona preta","bottom","calça","VOIP"],
["p012","Calça pantalona preta","bottom","calça","VOIP"],
["p044","Calça pantalona vinho","bottom","calça","OIP"],
["p046","Calça pantalona vinho","bottom","calça","OIP"],
["p024","Calça preta social","bottom","calça","VOIP"],
["p082","Calça verde militar","bottom","calça","OIP"],
["p173","Calça verde militar","bottom","calça","OIP"],
["p052","Saia branca com cinto","bottom","saia","VP"],
["p057","Saia longa branca de tule","bottom","saia","VP"],
["p065","Saia longa branca de tule","bottom","saia","VP"],
["p197","Saia midi animal print","bottom","saia","VOP"],
["p198","Saia midi animal print","bottom","saia","VOP"],
["p073","Saia midi branca acetinada","bottom","saia","VP"],
["p179","Saia midi marrom franzida","bottom","saia","VOP"],
["p014","Saia preta com cinto dourado","bottom","saia","VOIP"],
["item_111","Saia xadrez cinza","bottom","saia","OI"],
["p100","Short bege","bottom","short","VP"],
["p031","Short branco com botões","bottom","short","VP"],
["p214","Short branco com botões","bottom","short","VP"],
["p045","Short branco com laço","bottom","short","VP"],
["p129","Short caramelo de alfaiataria","bottom","short","VP"],
["g039","Short creme de alfaiataria","bottom","short","VP"],
["p090","Short jeans claro com cinto","bottom","short","VP"],
["p064","Short jeans escuro","bottom","short","VP"],
["p055","Short marrom canelado","bottom","short","VP"],
["p001","Short preto de alfaiataria","bottom","short","VP"],
["p006","Short preto de alfaiataria","bottom","short","VP"],
["p008","Short preto de alfaiataria","bottom","short","VP"],
["p117","Short xadrez tweed","bottom","short","OP"],
["p169","Short xadrez tweed","bottom","short","OP"],
["p084","Macaquinho azul estampado","vestido","macaquinho","VP"],
["p095","Vestido chemise terracota","vestido","vestido","OP"],
["p020","Vestido de veludo verde","vestido","vestido","OI"],
["p081","Vestido floral azul","vestido","vestido","VP"],
["p168","Vestido longo verde sálvia","vestido","vestido","VP"],
["p074","Vestido midi branco","vestido","vestido","VP"],
["p103","Vestido midi floral rosa","vestido","vestido","VP"],
["p029","Vestido preto com saia de couro","vestido","vestido","OI"],
["p017","Vestido preto gola alta","vestido","vestido","OI"],
["p015","Vestido preto manga transparente","vestido","vestido","OI"],
["p026","Vestido preto manga transparente","vestido","vestido","OI"],
["p076","Vestido turquesa estampado","vestido","vestido","V"],
["p155","Blazer camel","casaco","blazer","OIP"],
["g034","Blazer camel de alfaiataria","casaco","blazer","OIP"],
["g037","Blazer caqui","casaco","blazer","OIP"],
["p121","Blazer cinza mescla","casaco","blazer","OIP"],
["g033","Blazer creme aberto","casaco","blazer","VOP"],
["p145","Blazer mostarda","casaco","blazer","OP"],
["p137","Blazer pink","casaco","blazer","VP"],
["p016","Blazer preto acetinado","casaco","blazer","OI"],
["p167","Blazer tweed bege","casaco","blazer","OIP"],
["g036","Blazer verde oliva","casaco","blazer","OIP"],
["p033","Blazer vinho com cinto","casaco","blazer","OI"],
["p124","Blazer xadrez marrom","casaco","blazer","OI"],
["p127","Blazer xadrez marrom","casaco","blazer","OI"],
["p056","Cardigã creme de malha","casaco","cardigã","OP"],
["p193","Cardigã creme de malha","casaco","cardigã","OP"],
["p143","Jaqueta acolchoada bege","casaco","jaqueta","OI"],
["p042","Jaqueta de couro preta","casaco","jaqueta","OI"],
["p105","Jaqueta jeans clara","casaco","jaqueta","VOP"],
["p106","Jaqueta militar com pelo","casaco","jaqueta","OI"],
["p027","Jaqueta utilitária preta","casaco","jaqueta","OI"],
["p030","Parka preta com capuz","casaco","jaqueta","OI"],
["p080","Kimono floral manga ampla","casaco","kimono","VP"],
["p062","Kimono floral preto","casaco","kimono","VP"],
["p148","Casaco camel longo","casaco","sobretudo","OI"],
["p153","Casaco camel trespassado","casaco","sobretudo","I"],
["p079","Bota branca de neve","calcado","bota","I"],
["p034","Bota preta cano alto","calcado","bota","OI"],
["p041","Coturno preto","calcado","bota","OI"],
["p038","Coturno preto anabela","calcado","bota","OI"],
["p071","Chinelo branco","calcado","chinelo","V"],
["p060","Chinelo preto","calcado","chinelo","V"],
["p096","Chinelo preto com brilho","calcado","chinelo","V"],
["p150","Rasteira dourada","calcado","sandália","VP"],
["p176","Rasteira dourada","calcado","sandália","VP"],
["p119","Sandália branca salto bloco","calcado","sandália","VP"],
["p175","Sandália branca salto bloco","calcado","sandália","VP"],
["p087","Sandália gladiadora preta","calcado","sandália","VP"],
["item_092","Sandália gladiadora preta","calcado","sandália","VP"],
["p157","Sandália nude com glitter","calcado","sandália","VP"],
["p164","Sandália nude com glitter","calcado","sandália","VP"],
["p158","Sandália pink salto fino","calcado","sandália","VP"],
["p039","Mocassim preto com fivela","calcado","sapato","OIP"],
["p078","Tênis branco","calcado","tênis","VOIP"],
["p061","Tênis branco chunky","calcado","tênis","VOIP"],
["p032","Tênis preto esportivo","calcado","tênis","VOIP"],
["p151","Bolsa bege estruturada","acessorio","bolsa","VOIP"],
["p152","Bolsa bege estruturada","acessorio","bolsa","VOIP"],
["p172","Bolsa bege estruturada","acessorio","bolsa","VOIP"],
["p149","Bolsa de couro marrom","acessorio","bolsa","VOIP"],
["p195","Bolsa de couro marrom","acessorio","bolsa","VOIP"],
["p040","Bolsa de notebook preta","acessorio","bolsa","VOIP"],
["p093","Bolsa preta estruturada","acessorio","bolsa","VOIP"],
["p156","Mochila caramelo","acessorio","bolsa","VOIP"],
["p160","Mochila caramelo","acessorio","bolsa","VOIP"],
["p162","Mochila caramelo","acessorio","bolsa","VOIP"],
["p159","Cinto marrom fino","acessorio","cinto","VOIP"],
["p118","Cinto marrom fivela dourada","acessorio","cinto","VOIP"],
["p180","Cinto marrom fivela dourada","acessorio","cinto","VOIP"],
["p075","Cinto marrom fivela prateada","acessorio","cinto","VOIP"],
["p138","Cinto preto com tachas douradas","acessorio","cinto","VOIP"],
["p102","Cinto preto fivela dourada","acessorio","cinto","VOIP"],
["p132","Cinto preto fivela western","acessorio","cinto","VOIP"],
["p140","Cinto preto fivela western","acessorio","cinto","VOIP"],
["p189","Cinturão corrente dourada","acessorio","cinto","VOIP"],
["p207","Cinturão corrente dourada","acessorio","cinto","VOIP"],
["p068","Cachecol marrom com franjas","acessorio","lenço","OI"],
["p083","Echarpe preta","acessorio","lenço","OI"],
["p125","Lenço estampado dourado","acessorio","lenço","OIP"],
["p123","Lenço pied-de-poule","acessorio","lenço","OI"],
["p122","Lenço vermelho de Roma","acessorio","lenço","OI"],
["p171","Lenço vermelho de Roma","acessorio","lenço","OI"],
["p215","Óculos de grau dourado","acessorio","óculos","VOIP"],
["p112","Óculos gatinho bege","acessorio","óculos","VP"],
["p182","Óculos redondo dourado","acessorio","óculos","VOP"],
["p144","Argolas douradas","joia","brinco","VOIP"],
["p174","Argolas douradas","joia","brinco","VOIP"],
["p184","Colar corrente grossa","joia","colar","VOIP"],
["p190","Colar corrente grossa","joia","colar","VOIP"],
["p194","Colar dourado com medalha","joia","colar","VOIP"],
["p206","Colar dourado com pingente redondo","joia","colar","VOIP"],
["p209","Colar dourado duplo fino","joia","colar","VOIP"],
["p183","Colar dourado três fios","joia","colar","VOIP"],
["p003","Gorro preto","chapeu","gorro","I"]
];
