// [arquivo, nome, categoria, subcategoria, estações(V O I P), novo?]
window.CATALOGO = [
["item_000","Calça pantalona vinho","bottom","calça","OIP"],
["item_001","Colar corrente com medalha","acessorio","joia","VOIP"],
["item_002","Óculos redondo dourado","acessorio","óculos","VOP"],
["item_003","Camiseta preta com logo","top","camiseta","VOP"],
["item_004","Blazer camel","casaco","blazer","OIP"],
["item_005","Blazer vinho com cinto","casaco","blazer","OI"],
["item_006","Bolsa de couro marrom","acessorio","bolsa","VOIP"],
["item_007","Casaco camel longo","casaco","sobretudo","OI"],
["item_008","Gola alta preta canelada","top","gola alta","OI"],
["item_009","Calça pantalona branca","bottom","calça","VP"],
["item_010","Cardigã creme de malha","casaco","cardigã","OP"],
["item_011","Jaqueta de couro preta","casaco","jaqueta","OI"],
["item_012","Bota preta cano alto","calcado","bota","OI"],
["item_013","Top acetinado cobre","top","regata","VP"],
["item_014","Blusa floral amarrada","top","blusa","VP"],
["item_015","Short bege","bottom","short","VP"],
["item_016","Sandália branca salto bloco","calcado","sandália","VP"],
["item_017","Óculos gatinho preto","acessorio","óculos","VP"],
["item_018","Tomara que caia preto","top","tube","VP"],
["item_019","Tênis preto esportivo","calcado","tênis","VOIP"],
["item_020","Regata branca de alcinha","top","regata","VP"],
["item_021","Short marrom canelado","bottom","short","VP"],
["item_022","Camiseta marrom Salmos","top","camiseta","VOP"],
["item_023","Blazer tweed bege","casaco","blazer","OIP"],
["item_024","Gola alta caramelo sem manga","top","gola alta","OP"],
["item_025","Top preto floral bordado","top","cropped","VP"],
["item_026","Tomara que caia marrom","top","tube","VP"],
["item_027","Short caramelo de alfaiataria","bottom","short","VP"],
["item_028","Coturno preto anabela","calcado","bota","OI"],
["item_029","Lenço estampado dourado","acessorio","lenço","OIP"],
["item_030","Camisa estampa abstrata","top","camisa","VP"],
["item_031","Saia midi preta estampada","bottom","saia","VOP"],
["item_032","Saia branca com cinto","bottom","saia","VP"],
["item_033","Calça pantalona preta","bottom","calça","VOIP"],
["item_034","Saia midi animal print","bottom","saia","VOP"],
["item_035","Tomara que caia vinho","top","tube","VOP"],
["item_036","Colar dourado três fios","acessorio","joia","VOIP"],
["item_037","Óculos gatinho bege","acessorio","óculos","VP"],
["item_038","Blusa vermelha drapeada","top","blusa","VOP"],
["item_039","Top marrom com torção","top","cropped","VP"],
["item_040","Top verde musgo","top","cropped","VP"],
["item_041","Rasteira dourada","calcado","sandália","VP"],
["item_042","Chinelo preto com brilho","calcado","chinelo","V"],
["item_043","Tênis branco","calcado","tênis","VOIP"],
["item_044","Short jeans escuro","bottom","short","VP"],
["item_045","Camisa caqui oversized","top","camisa","OP"],
["item_046","Camisa do Grêmio","top","camiseta","VOIP"],
["item_047","Blazer preto acetinado","casaco","blazer","OI"],
["item_048","Vestido midi branco","vestido","vestido","VP"],
["item_049","Colar corrente grossa","acessorio","joia","VOIP"],
["item_050","Macaquinho azul estampado","vestido","macaquinho","VP"],
["item_051","Cinto marrom fivela dourada","acessorio","cinto","VOIP"],
["item_052","Lenço vermelho de Roma","acessorio","lenço","OI"],
["item_053","Vestido preto com saia de couro","vestido","vestido","OI"],
["item_054","Cinturão corrente dourada","acessorio","cinto","VOIP"],
["item_055","Bota branca de neve","calcado","bota","I"],
["item_056","Tênis branco chunky","calcado","tênis","VOIP"],
["item_057","Gorro preto","acessorio","gorro","I"],
["item_058","Mocassim preto com fivela","calcado","sapato","OIP"],
["item_059","Cachecol marrom com franjas","acessorio","cachecol","OI"],
["item_060","Jaqueta acolchoada bege","casaco","jaqueta","OI"],
["item_061","Vestido preto gola alta","vestido","vestido","OI"],
["item_062","Casaco camel trespassado","casaco","sobretudo","I"],
["item_063","Blusa branca manga bufante","top","blusa","VOP"],
["item_064","Gola alta preta cropped","top","gola alta","OI"],
["item_065","Blazer cinza mescla","casaco","blazer","OIP"],
["item_066","Bolsa bege estruturada","acessorio","bolsa","VOIP"],
["item_067","Kimono floral preto","casaco","kimono","VP"],
["item_068","Camiseta preta básica","top","camiseta","VOP"],
["item_069","Camisa bege de linho","top","camisa","VP"],
["item_070","Blusa verde oliva bufante","top","blusa","OP"],
["item_071","Camisa branca manga 3/4","top","camisa","VOP"],
["item_072","Corselet floral bege","top","cropped","VP"],
["item_073","Short jeans claro com cinto","bottom","short","VP"],
["item_074","Top verde com amarração","top","cropped","VP"],
["item_075","Top turquesa lifemom","top","cropped","V"],
["item_076","Chinelo branco","calcado","chinelo","V"],
["item_077","Tomara que caia creme","top","tube","VP"],
["item_078","Blusa preta ombro a ombro","top","blusa","VOP"],
["item_079","Suéter branco de tricô","top","suéter","OI"],
["item_080","Blusa preta manga bufante","top","blusa","OP"],
["item_081","Corselet terracota","top","cropped","VP"],
["item_082","Short preto de alfaiataria","bottom","short","VP"],
["item_083","Chinelo preto","calcado","chinelo","V"],
["item_084","Jaqueta jeans clara","casaco","jaqueta","VOP"],
["item_085","Vestido de veludo verde","vestido","vestido","OI"],
["item_086","Sandália nude com glitter","calcado","sandália","VP"],
["item_087","Vestido floral azul","vestido","vestido","VP"],
["item_088","Saia midi marrom franzida","bottom","saia","VOP"],
["item_089","Top roxo com laço","top","cropped","VP"],
["item_090","Short xadrez tweed","bottom","short","OP"],
["item_091","Short jeans preto","bottom","short","VP"],
["item_092","Sandália gladiadora preta","calcado","sandália","VP"],
["item_093","Top pink de paetê","top","cropped","V"],
["item_094","Argolas douradas","acessorio","joia","VOIP"],
["item_095","Top branco com laço","top","cropped","VP"],
["item_096","Echarpe preta","acessorio","cachecol","OI"],
["item_097","Cinto preto fivela western","acessorio","cinto","VOIP"],
["item_098","Short branco com botões","bottom","short","VP"],
["item_099","Camisa do Grêmio Suárez","top","camiseta","VOIP"],
["item_100","Blazer pink","casaco","blazer","VP"],
["item_101","Blazer xadrez marrom","casaco","blazer","OI"],
["item_102","Cropped branco com recorte","top","cropped","VP"],
["item_103","Mochila caramelo","acessorio","bolsa","VOIP"],
["item_104","Saia de couro preta","bottom","saia","OI"],
["item_105","Blazer mostarda","casaco","blazer","OP"],
["item_106","Sandália pink salto fino","calcado","sandália","VP"],
["item_107","Camisa listrada com flores","top","camisa","VP"],
["item_108","Lenço pied-de-poule","acessorio","lenço","OI"],
["item_109","Camisa xadrez preto e branco","top","camisa","OIP"],
["item_110","Blusa de tule transparente","top","blusa","OP"],
["item_111","Saia xadrez cinza","bottom","saia","OI"],
["item_112","Jaqueta militar com pelo","casaco","jaqueta","OI"],
["item_113","Blusa azul com bolsos","top","blusa","OP"],
["item_114","Blusa de girassóis","top","blusa","V"],
["item_115","Bolsa de notebook preta","acessorio","bolsa","VOIP"],
["item_116","Vestido chemise terracota","vestido","vestido","OP"],
["item_117","Calça preta social","bottom","calça","VOIP"],
["item_118","Tomara que caia listrado","top","tube","VP"],
["item_119","Gola alta cinza com amarração","top","gola alta","OI"],
["item_120","Corselet vermelho acetinado","top","cropped","VOP"],
["item_121","Blusa vermelha sem manga","top","blusa","VP"],
["item_122","Top zigue-zague","top","cropped","VP"],
["item_123","Top listrado com folhagem","top","cropped","V"],
["item_124","Vestido turquesa estampado","vestido","vestido","V"],
["item_125","Short branco com laço","bottom","short","VP"],
["item_126","Saia longa branca de tule","bottom","saia","VP"],
["item_127","Blusa preta decote V manga longa","top","blusa","OIP"],
["item_128","Cropped branco manga bufante","top","cropped","VOP"],
["item_129","Kimono floral manga ampla","casaco","kimono","VP"],
["item_130","Blusa preta com laço","top","blusa","OP"],
["item_131","Camiseta branca com estampa","top","camiseta","VP"],
["item_132","Parka preta com capuz","casaco","jaqueta","OI"],
["item_143","Calça estampa abstrata","bottom","calça","VP"],
["item_144","Calça caramelo jogger","bottom","calça","OP"],
["new_jaqueta_couro_marrom","Jaqueta de couro marrom","casaco","jaqueta","OI",2],
["new_golaalta_vinho","Gola alta vinho","top","gola alta","OI",2],
["new_golaalta_nude","Gola alta nude","top","gola alta","OI",2],
["new_golaalta_marrom","Gola alta marrom","top","gola alta","OI",1],
["new_golaalta_chumbo","Gola alta chumbo","top","gola alta","OI",1],
["new_golaalta_offwhite","Gola alta off-white","top","gola alta","OI",1],
["new_body_marrom","Body manga longa marrom","top","blusa","OIP",1],
["new_body_preto","Body preto manga longa","top","blusa","OIP",1],
["new_relogio_dourado","Relógio dourado","acessorio","joia","VOIP",1]
];
